name: job level environment variable

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build-Job
    runs-on: ubuntu-latest
    env:
        firstname: 'sai praneeth'
        lastname: 'senigapalli'
    steps:
      - name: declare env variable
        run: echo "full name is $firstname $lastname"
      - name: run df command
        run: df -h
      - name: display first name
        run: echo "firstname is $firstname"
      - name: display last name
        run: echo "last name is $lastname"
    
    
  