name: matrix fail fast tutorial

on:
    workflow_dispatch:

jobs:
    Build:
        name: Build-Job
        strategy:
            matrix:
                fail-fast: false
                os: [ubuntu-latest,ubuntu-oldest,windows-latest]
        runs-on:
            ${{ matrix.os}}
        steps:
            - name: running command
              run: echo "running in ${{ matrix.os }}"