name: max parallel tutorial

on:
    workflow_dispatch:

jobs:
    Build:
        name: Build-Job
        runs-on: ${{matrix.os}}
        strategy:
            max-parallel: 2
            fail-fast: fast
            matrix:
                os: [ubuntu-latest,ubuntu-22.04,ubuntu-24.04,windows-latest]
                node: [16,18]
        steps:
            - name: matrix job
              run: echo "current we are running ${{matrix.node}}"

