name: testing the secrets

on:
    workflow_dispatch:

env:
    DB_PASSWORD: ${{ secrets.DB_PASSWORD}}

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build-Job
        steps:
            - name: using secrets
              run: echo "the password is $DB_PASSWORD"