name: step level environment variable

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build-Job
    runs-on: ubuntu-latest
    steps:
      - name: declare env variable
        env:
          firstname: 'sai praneeth'
          lastname: 'senigapalli'
        run: |
          echo "full name is $firstname $lastname"

      - name: try to display again
        run: echo "full name is $firstname $lastname"
        continue-on-error: true
        
      - name: run df command
        run: df -h