name: sai praneeth workflow

on:
  push:
    paths:
      - '.github/workflows/test2.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building Job
    steps:
      - name: running simple command
        run: echo "hello worldd"
      - name: code checkout
        uses: actions/checkout@v4
      - name: read content
        run: cat devops.txt
