name: this is 3rd yaml file

on:  
  push:
    paths:
        - '.github/workflows/test3.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: we will run df command,
              run: df -h