name: this is 3rd yaml file

on:  
  push:
    paths:
        - '.github/workflows/test2.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: we will run date command,
              run: date