name: sai praneeth workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building Job
    steps:
      - name: running simple command
        run: echo "hello worldd"
      - name: code checkout
        uses: actions/checkout@v4
      - name: read content
        run: cat devops.txt

      - name: wrong command
        run: daate

      - name: always run
        if: always()
        run: date

        
