name: this is 3rd yaml file

on:  
  push:
    paths:
        - '.github/workflows/test3.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: we will run df command,
              run: du

            - name: task to create a file
              run: echo "sai praneeth" > abc.txt
            
            - name: display content
              run: cat abc.txt