name: this is 3rd yaml file

on:  
  workflow_dispatch:

jobs:
    build:
        name: Build Job
        runs-on: ubuntu-latest
        steps:
            - name: we will run df command,
              run: df -h

            - name: task to create a file
              run: echo "sai praneeth" > abc.txt
            
            - name: display content
              run: cat abc.txt