name: with matrix strategy

on:
    workflow_dispatch:

jobs:
    Build:
        name: Build-Job
        runs-on: ${{ matrix.os }}
        strategy:
            matrix: 
                os: [ubuntu-latest,windows-latest,ubuntu-24.04]
        steps:
            - name: running
              run: echo "Running in ${{ matrix.os }}"