name: workflow level environment variable

on: 
  workflow_dispatch:

env:
    firstname: 'saipraneeth'
    lastname: 'senigapalli'

jobs:
  build:
    name: Build-Job
    runs-on: ubuntu-latest
    steps:

      - name: try to display name
        run: echo "full name is $firstname $lastname"
        continue-on-error: true
        
      - name: run df command
        run: df -h
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: display name
          run: echo "full name is $firstname $lastname"